# This file was generated by GoReleaser. DO NOT EDIT.
cask "a22r" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "5f5d9532778b1d5f0d0884e222ea38941b97c701496998ce6e99add1adf0c2ca"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5eb9a5ec5e40a92dea6ad64b91fc7532be24695385f89bad4d8e65b04e5003c"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e0d8b73e6de2d78e67d8e6534f606d0836327e9609e6891f1fbbd5c909ac6160"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f7006fca2c2fa454abeeffa89497be02ac6b867f65342dc1548b5c916d7015c"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_linux_amd64.tar.gz"
    end
  end

  name "a22r"
  desc "Inspect and update Azure DevOps classic release pipelines in bulk"
  homepage "https://github.com/theomerkaratas/azure-devops-batch-operator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a22r"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/a22r"]
      config_dir = Pathname.new(ENV["XDG_CONFIG_HOME"] || (Pathname.new(Dir.home)/".config"))/"a22r"
      config_file = config_dir/"config.yml"
      example_file = staged_path/"config.example.yml"
      onprem_example = staged_path/"config.onprem.example.yml"

      config_dir.mkpath
      if !config_file.exist? && example_file.exist?
        FileUtils.cp(example_file, config_file)
        File.chmod(0600, config_file)
      end
      FileUtils.cp(example_file, config_dir/"config.example.yml") if example_file.exist?
      FileUtils.cp(onprem_example, config_dir/"config.onprem.example.yml") if onprem_example.exist?
    end
  end

  # No zap stanza required
end
