# This file was generated by GoReleaser. DO NOT EDIT.
cask "a22r" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "e4a4a50c0f4c17a7663158b8c28298f9617c6dd7cdf26052c966619413e2e8fa"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "83f995cc686eac07171880fed0d00ee187701d59d53bece25e6f96a975aeaae1"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4888e2a831fbf8249509a736353e1756a98c4370e85d30aed2015d1fa55c9420"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2252ee889a97c5cb219cc8af68468f956c3c10540d85b3d3d0a24ca895cf6e2a"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_linux_amd64.tar.gz"
    end
  end

  name "a22r"
  desc "Inspect and update Azure DevOps classic release pipelines in bulk"
  homepage "https://github.com/theomerkaratas/azure-devops-batch-operator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a22r"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/a22r"]
    end
  end

  # No zap stanza required
end
