# This file was generated by GoReleaser. DO NOT EDIT.
cask "a22r" do
  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "784a55ae038ccba4d1b4210603622021862ad7cdf147eeaffcbae8388782f960"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f524de0d5999dcf3d6bee75b79d3389cc1d95ade312e41be006a2e8a3610e3fe"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b03629453d56895e9782004316065faee37ff87f2245a40c65e4b7c595f7b3bb"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ceed054c62d090410b9790c12dde7ab1303889b1acc14f278609b37aa549a2a8"
      url "https://github.com/theomerkaratas/azure-devops-batch-operator/releases/download/v#{version}/a22r_linux_amd64.tar.gz"
    end
  end

  name "a22r"
  desc "Inspect and update Azure DevOps classic release pipelines in bulk"
  homepage "https://github.com/theomerkaratas/azure-devops-batch-operator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a22r"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/a22r"]
      config_dir = Pathname.new(ENV["XDG_CONFIG_HOME"] || (Pathname.new(Dir.home)/".config"))/"a22r"
      config_file = config_dir/"config.yml"
      example_file = staged_path/"config.example.yml"
      onprem_example = staged_path/"config.onprem.example.yml"

      config_dir.mkpath
      if !config_file.exist? && example_file.exist?
        FileUtils.cp(example_file, config_file)
        File.chmod(0600, config_file)
      end
      FileUtils.cp(example_file, config_dir/"config.example.yml") if example_file.exist?
      FileUtils.cp(onprem_example, config_dir/"config.onprem.example.yml") if onprem_example.exist?
    end
  end

  # No zap stanza required
end
